const express = require("express")
const app = express()
const users = require("../routes/users")
const despesas = require("../routes/despesas.js")
const entradas = require("../routes/entradas.js")
const metas = require ('../routes/metas')
let cors = require('cors');
require("../database/db")
app.use(cors())
app.use(express.json())
app.use(express.urlencoded({ extended: false }));
app.use("/users",users)
app.use("/despesas",despesas)
app.use("/metas",metas)
app.use("/entradas",entradas)
app.get("/",(req,res) =>{res.send("rodando")})
app.listen(3001,()=> console.log("Iniciou o projeto"))
